### ISSUE TITLE
The future of RioSharp and current status

### ISSUE THREAD

**Issue by Scooletz** [aL3891/RioSharp#3]
This project is described as a spin-off Ben Adams' work on the Kestrel communication. I've heard that RIO might be next thing, especially when combined with channels. What are your plans and the roadmap?

**Comment by aL3891** [comment]
This project is largely obsoleted by the pipelines work going on in corefxlab repo, there are efforts there to make a RIO implementation that runs on pipelines and I suggest using that instead of this. 
I've left this up mostly as a reference and also for udp support witch is not supported in corefxlab yet, although that might be coming down the line

**Comment by Scooletz** [comment]
UDP is the most interesting part, as I'm doing a message shipping similar to Aeron. Anyway, will either fork this or send a PR if I don't find pipelines work usable.
